repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.9
  hooks:
    - name: Run python linter
      id: ruff
      args: [ --fix ]
      types: [ python ]
    - name: Run python formatter
      id: ruff-format
      args: [ ]
      types: [ python ]
